name: kitchen-tests

on: [push, workflow_dispatch]

jobs:
  docker:
    if: "!contains(github.event.commits[0].message, '[skip docker]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: brownccv/terraform-kitchen-template
          tags: latest
  test:
    needs: [docker]
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    container: brownccv/terraform-kitchen-template:latest
    steps:
    - uses: actions/checkout@v1
    - name: Run Kitchen
      run: kitchen test

